DEVICE_PATH := device/samsung/gtel3g

# Архитектура
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

# Загрузчик
TARGET_BOOTLOADER_BOARD_NAME := sc8830
TARGET_NO_BOOTLOADER := true

# Платформа
TARGET_BOARD_PLATFORM := sc8830

# Утверждение OTA обновления
TARGET_OTA_ASSERT_DEVICE := SM-T561,SM-T560,gtel3g,gtelwifi,gtel3gxx,gtelwifixx,smt561,smt560

# Ядро и DTB
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DT_IMAGE := $(DEVICE_PATH)/prebuilt/dt.img
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_OFFSET := 0x01000000

# Использование предкомпилированного ядра и DTB
TARGET_IGNORE_PREBUILT_KERNEL_CHECKSUM := true
BOARD_KERNEL_SEPARATED_DT := true

# Форсированное использование предкомпилированного ядра
TARGET_BUILD_KERNEL_WITHOUT_KERNEL_CONFIG := true

# Гарантированная чистка промежуточных результатов
INTERNAL_KERNEL_CLEANING := true

# Увеличение размеров блоков flash
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Специфичные флаги TWRP
BOARD_USE_CUSTOM_RECOVERY_FONT := roboto_10x18.h
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_SDCARD_ON_DATA := true
SP1_NAME := internal_sd
SP1_BACKUP_METHOD := files
SP1_MOUNTABLE := 1
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun%d/file
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TW_THEME := portrait_hdpi
TW_INTERNAL_STORAGE_PATH := /data/media/0
TW_INTERNAL_STORAGE_MOUNT_POINT := data
TW_EXTERNAL_STORAGE_PATH := /storage/sdcard1
TW_EXTERNAL_STORAGE_MOUNT_POINT := external_sd
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_FLASH_FROM_STORAGE := true
TW_MAX_BRIGHTNESS := 255
TW_EXTRA_LANGUAGES := false
TW_DEFAULT_LANGUAGE := ru
TW_EXCLUDE_APEX := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_LPTOOLS := true
TW_EXCLUDE_LPDUMP := true
TW_EXCLUDE_SUPERSU := true
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TW_NO_USB_STORAGE := true
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
RECOVERY_GRAPHICS_FORCE_USE_LINELENGTH := true
#TW_INCLUDE_CRYPTO := true
# Версия/мантейнер
TW_DEVICE_VERSION := SM-T561 by SK
